{% set name = "mill" %}
{% set version = "0.11.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/com-lihaoyi/{{ name }}
  git_rev: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - curl
    - maven
    - openjdk =17
    - sed
  run:
    - openjdk

test:
  commands:
    - mill --help

about:
  home: https://mill-build.com
  license: MIT
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Your shiny new Java/Scala build tool!
  dev_url: https://github.com/com-lihaoyi/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
