context:
  version: 0.11.8

package:
  name: mill
  version: ${{ version }}

source:
  git: https://github.com/com-lihaoyi/mill
  tag: ${{ version }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - curl
    - git
    - maven
    - openjdk =17
    - sed
  run:
    - openjdk

tests:
  - script:
      - mill --help

about:
  license: MIT
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Your shiny new Java/Scala build tool!
  homepage: https://mill-build.com
  repository: https://github.com/com-lihaoyi/mill

extra:
  recipe-maintainers:
    - danielnachun
